services:
    auth.provider.medusa:
        class: TRMN\medusaauth\auth\provider\medusa
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@user'
            - '@language.loader'
        tags:
            - { name: auth.provider }